version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: "hack-browser-data-windows-amd64"
    main: ./cmd/hack-browser-data/
    binary: hack-browser-data
    env:
      - CGO_ENABLED=0
    goos: [windows]
    goarch: [amd64]
    tags:
      - abe_embed
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.buildDate={{.Date}}

  - id: "hack-browser-data"
    main: ./cmd/hack-browser-data/
    binary: hack-browser-data
    env:
      - CGO_ENABLED=0
    goos: [windows, linux, darwin]
    goarch: [amd64, "386", arm, arm64]
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: amd64
      - goos: windows
        goarch: "386"
      - goos: windows
        goarch: arm
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.buildDate={{.Date}}

archives:
  - id: "archive"
    ids:
      - hack-browser-data-windows-amd64
      - hack-browser-data
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE
    name_template: >-
      hack-browser-data-
      {{- if eq .Os "darwin" }}osx
      {{- else if eq .Os "linux" }}linux
      {{- else if eq .Os "windows" }}windows
      {{- else }}{{ .Os }}{{ end }}-
      {{- if eq .Arch "amd64" }}64bit
      {{- else if eq .Arch "386" }}32bit
      {{- else if eq .Arch "arm64" }}arm64
      {{- else if eq .Arch "arm" }}arm
      {{- else }}{{ .Arch }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore\\(deps\\):"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
checksum:
  name_template: "checksums-v{{ .Version }}.txt"
  algorithm: sha256

brews:
  - name: hack-browser-data
    homepage: "https://github.com/moonD4rk/HackBrowserData"
    description: "Extract and decrypt browser data from multiple browsers"
    license: "MIT"
    directory: Formula
    skip_upload: auto
    repository:
      owner: moonD4rk
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: "github-actions[bot]"
      email: "github-actions[bot]@users.noreply.github.com"
    commit_msg_template: "brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    install: |
      bin.install "hack-browser-data"
    test: |
      system "#{bin}/hack-browser-data", "version"

release:
  prerelease: auto
