name: Feature Request
description: Suggest an idea for this project
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why is this feature needed?
      description: Describe the problem this feature would solve or the use case it enables.
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: If you have an idea for how this could be implemented, describe it here.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked the [existing issues](https://github.com/moonD4rk/HackBrowserData/issues) for similar requests.
          required: true
