// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs layout_gen.go

package bootstrap

const (
	MarkerOffset         = 0x28
	KeyStatusOffset      = 0x29
	KeyStatusReady       = 0x1
	ExtractErrCodeOffset = 0x2a
	HResultOffset        = 0x2c
	ComErrOffset         = 0x30
	KeyOffset            = 0x40
	KeyLen               = 0x20

	ImpLoadLibraryAOffset   = 0x40
	ImpGetProcAddressOffset = 0x48
	ImpVirtualAllocOffset   = 0x50
	ImpVirtualProtectOffset = 0x58
	ImpNtFlushICOffset      = 0x60

	MarkMZFound      = 0x2
	MarkImportsOK    = 0x5
	MarkAllocOK      = 0x6
	MarkCopied       = 0x7
	MarkRelocated    = 0x8
	MarkImportsFixed = 0x9
	MarkPermissions  = 0xa
	MarkCacheFlushed = 0xb
	MarkDone         = 0xff
	MarkErrImports   = 0xe3
	MarkErrAlloc     = 0xe4

	ErrOk             = 0x0
	ErrBasename       = 0x1
	ErrBrowserUnknown = 0x2
	ErrEnvMissing     = 0x3
	ErrBase64         = 0x4
	ErrBstrAlloc      = 0x5
	ErrComCreate      = 0x6
	ErrDecryptData    = 0x7
	ErrKeyLen         = 0x8
)
